name: Provision & Déploiement API

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provisionner l'infra GCP
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Créer credentials.json depuis le secret base64
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > ${{ github.workspace }}/terraform/credentials.json

      - name: Plan Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform plan \
            -var="gcp_credentials=${{ github.workspace }}/terraform/credentials.json" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file="terraform.tfvars"

      - name: Appliquer Terraform
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="gcp_credentials=${{ github.workspace }}/terraform/credentials.json" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file="terraform.tfvars"

      - name: Générer inventory.ini pour Ansible
        working-directory: terraform
        run: |
          IP=$(terraform output -raw vm_external_ip)
          echo "[api]" > ../ansible/inventory.ini
          echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../ansible/inventory.ini

  ansible:
    name: Déployer l'API avec Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Ansible et SSH client
        run: |
          sudo apt update
          sudo apt install -y ansible openssh-client

      - name: Ajouter la clé SSH privée
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Exécuter le playbook Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --ssh-extra-args="-o StrictHostKeyChecking=no"

  snapshot:
    name: Snapshot du disque GCP
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Installer gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Créer un snapshot du disque
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          gcloud compute disks snapshot vm-disk \
            --snapshot-names=snapshot-api-$TIMESTAMP \
            --zone=europe-west9-b \
            --project=${{ secrets.GCP_PROJECT_ID }}